name: Test
on:
  delete:
  pull_request:
  push:
    branches:
      - master

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: usherlabs/monorepo-package-mirror-action@main
        with:
          target_repo_url: https://github.com/outerlook/mirror-test-dest.git
          main_branch: master
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}